_wandb:
    value:
        cli_version: 0.26.1
        e:
            iacx7vv678wbnwa942t3zbc12qji1f79:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    macModel: Mac16,8
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "5368709120"
                codePath: /Users/sburtsev/Documents/hse/смадимо/гп5/gp_5_DL/notebooks/mlp_tab.ipynb
                codePathLocal: mlp_tab.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "162856828928"
                email: keyoflife811@gmail.com
                executable: /Library/Developer/CommandLineTools/usr/bin/python3
                git:
                    commit: c6b40079fcb58b386b6fde7b5307a5403bcbd7a8
                    remote: https://github.com/burtsev-sa/gp_5_DL
                host: MacBook-Pro-de-Stanislav.local
                memory:
                    total: "25769803776"
                os: macOS-26.5.1-arm64-arm-64bit
                program: /Users/sburtsev/Documents/hse/смадимо/гп5/gp_5_DL/notebooks/mlp_tab.ipynb
                python: CPython 3.9.6
                root: /Users/sburtsev/Documents/hse/смадимо/гп5/gp_5_DL/notebooks
                startedAt: "2026-06-16T01:36:18.909861Z"
                writerId: iacx7vv678wbnwa942t3zbc12qji1f79
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.9.6
            "5": 0.26.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.26.1
            "13": darwin-arm64
entity:
    value: armntvs-d3v-student
lr:
    value: 0.001
model:
    value: |-
        Simple(
          (fc1): Linear(in_features=570, out_features=128, bias=True)
          (fc2): Linear(in_features=128, out_features=64, bias=True)
          (fc3): Linear(in_features=64, out_features=1, bias=True)
        )
num_epochs:
    value: 15
project:
    value: kolesa-cars
seed:
    value: 42
test_batch_size:
    value: 256
train_batch_size:
    value: 64
wandb:
    value: true
